
# cargo-features = ["panic-immediate-abort"]
[package]
name = "fuseidk"
version = "0.1.7"
edition = "2021"

[dependencies]
android_logger = { version = "0.15.0", default-features = false, optional = true}
atoi = { version = "2.0.0", optional = true }
bhook = { version = "0.1.0", git = "https://github.com/mcbegamerxx954/bhook" }
bstr = { version = "1.12.1", optional = true }
ctor = { version = "0.6.3", default-features = false }
cxx = { version = "1.0.128", optional = true }
jni = {version= "0.21.1", optional = true }
libc = "0.2.159"
libloading = {version ="0.9", optional = true}
log = "0.4.22"
materialbin = { git = "https://github.com/mcbegamerxx954/materialbin", version = "0.1.1", optional = true }
memchr = {version ="2.7.6",optional = true}
# ndk = { version = "0.9.0", default-features = false }
ndk-sys = "0.6.0"
notify = { version = "8.2.0", default-features = false, optional = true }
plt-rs = "0.3.0"
region = "3.0.2"
scroll = {version = "0.12.0", optional = true}
struson = { version = "0.6.0", optional = true }
tinypatscan = { git = "https://github.com/mcbegamerxx954/tinypatscan", version = "0.1.1", optional = true }
walkdir = { version = "2.5.0", optional = true }

# [profile.release]
# This lib gets called from nowhere and so unwinding = crash
# panic = "abort"

[profile.githubci]
inherits = "release"
strip = true
lto = "fat"
codegen-units = 1 
debug = false
panic = "abort"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.1.24"


[features]
default = ["mbl2","draco","logging","autofixing","jni"]
log_disable = ["log/release_max_level_off"]
logging = ["dep:android_logger"]
autofixing = ["dep:materialbin", "dep:scroll", "dep:memchr"]
jni = ["dep:jni"]
mbl2 = ["dep:cxx", "dep:atoi", "dep:bstr", "dep:tinypatscan"]
draco = ["dep:struson", "dep:walkdir", "dep:jni", "dep:libloading", "dep:notify"]


